In [68]:
import numpy as np

In [29]:
A = np.mgrid(0,0,0)

TypeError: 'MGridClass' object is not callable

In [4]:
A

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
a = np.linspace(0,5,6)
av = np.meshgrid(a)

In [25]:
a, av

(array([0., 1., 2., 3., 4., 5.]), [array([0., 1., 2., 3., 4., 5.])])

In [23]:
A@a

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 6 is different from 5)

In [69]:
x = np.linspace(0,5,6)
y = np.linspace(0,5,6)

In [70]:
xv, yv= np.meshgrid(x,y)

In [37]:
xv, yv

(array([[0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.]]),
 array([[0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5., 5.]]))

In [38]:
x = np.array[
    [[0,0,0],
    [0,1,0],
    [0,2,0],
    [1,0,0],
    [2,0,0],
    [2,1,0],
    [2,2,0]],
    [[0,0,2],
    [0,1,2],
    [0,2,2],
    [1,0,2],
    [2,0,2],
    [2,0,2],
    [2,1,2],
    [2,2,2]]
]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [40]:
xyz = np.array[
    [[0,0,0],
    [0,1,0],
    [0,2,0],
    [1,0,0],
    [1,2,0],
    [2,0,0],
    [2,1,0],
    [2,2,0]],
    [[0,0,0],
    [0,1,0],
    [0,2,0],
    [0,0,2],
    [0,1,2],
    [0,2,2],
    [0,1,0],
    [0,1,1]],
    [[2,0,0],
    [2,1,0],
    [2,2,0],
    [2,0,0],
    [2,1,0],
    [2,2,0],
    [2,1,2],
    [2,2,2]],
    
]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [57]:
import open3d as o3d
m = o3d.geometry.TriangleMesh.create_box(4,4,4)

x = m.vertices[0]
y = m.vertices[1]
z = m.vertices[2]



#m = o3d.geometry.TriangleMesh.create_cone(4,4,40)



In [59]:
xx, yy, zz = np.meshgrid(x,y,z)

In [67]:
p = np.meshgrid(x,y,z)
print(p.shape, p.size, p.dim)

AttributeError: 'list' object has no attribute 'shape'

In [65]:
xx.shape, xx.ndim

((3, 3, 3), 3)

In [66]:
np.stack(xx,yy,zz)

TypeError: only integer scalar arrays can be converted to a scalar index

In [63]:
zz

array([[[0., 0., 4.],
        [0., 0., 4.],
        [0., 0., 4.]],

       [[0., 0., 4.],
        [0., 0., 4.],
        [0., 0., 4.]],

       [[0., 0., 4.],
        [0., 0., 4.],
        [0., 0., 4.]]])

In [56]:
np.asarray(m.vertices), np.asarray(m.vertices).shape 

(array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  4.00000000e+00],
        [ 4.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 3.95075336e+00,  6.25737860e-01,  0.00000000e+00],
        [ 3.80422607e+00,  1.23606798e+00,  0.00000000e+00],
        [ 3.56402610e+00,  1.81596200e+00,  0.00000000e+00],
        [ 3.23606798e+00,  2.35114101e+00,  0.00000000e+00],
        [ 2.82842712e+00,  2.82842712e+00,  0.00000000e+00],
        [ 2.35114101e+00,  3.23606798e+00,  0.00000000e+00],
        [ 1.81596200e+00,  3.56402610e+00,  0.00000000e+00],
        [ 1.23606798e+00,  3.80422607e+00,  0.00000000e+00],
        [ 6.25737860e-01,  3.95075336e+00,  0.00000000e+00],
        [ 2.44929360e-16,  4.00000000e+00,  0.00000000e+00],
        [-6.25737860e-01,  3.95075336e+00,  0.00000000e+00],
        [-1.23606798e+00,  3.80422607e+00,  0.00000000e+00],
        [-1.81596200e+00,  3.56402610e+00,  0.00000000e+00],
        [-2.35114101e+00