#Pyvista

https://stackoverflow.com/questions/54898657/i-want-to-generate-a-mesh-from-a-point-cloud-in-python

In [22]:
import numpy as np
import pyvista as pv
import pandas as pd

"""
Gets the bounds configuration to make a PyVista 3d box
returns: bounding box of the cube. (xMin, xMax, yMin, yMax, zMin, zMax)
"""
def getBoxPointsBounds(centroid):
    spacing = 10
    bounds_min = centroid - spacing * 0.5
    bounds_max = centroid + spacing * 0.5
    return np.array([bounds_min[0], bounds_max[0], bounds_min[1], bounds_max[1], bounds_min[2], bounds_max[2]])

def getCubeCorners(center):
    bounds = getBoxPointsBounds(center)
    mesh = pv.Box(level=0, bounds=(bounds[0], bounds[1], bounds[2], bounds[3], bounds[4], bounds[5]))
    return mesh.points
points = getCubeCorners(np.array([15,5,595]))
points

pyvista_ndarray([[ 10.,   0., 590.],
                 [ 20.,   0., 590.],
                 [ 10.,  10., 590.],
                 [ 20.,  10., 590.],
                 [ 10.,   0., 600.],
                 [ 20.,   0., 600.],
                 [ 10.,  10., 600.],
                 [ 20.,  10., 600.]], dtype=float32)

In [23]:
csv = "ext_array.csv"
df = pd.read_csv(csv)

x = df[0:6].to_numpy()
x

array([[ 15.,   5., 595.],
       [  5.,  15., 595.],
       [ 25.,   5., 595.],
       [ 35.,   5., 595.],
       [ 45.,   5., 595.],
       [ 45.,  15., 595.]])

In [25]:
boxes = []

for point in x:
    points = getCubeCorners(point)
    print(points)
    for p in points:
        boxes.append(p)
    
x = np.array(boxes)
boxes, type(boxes), np.array(boxes).shape, x
    


[[  5.  -5. 585.]
 [ 15.  -5. 585.]
 [  5.   5. 585.]
 [ 15.   5. 585.]
 [  5.  -5. 595.]
 [ 15.  -5. 595.]
 [  5.   5. 595.]
 [ 15.   5. 595.]]
[[ 15.  -5. 585.]
 [ 25.  -5. 585.]
 [ 15.   5. 585.]
 [ 25.   5. 585.]
 [ 15.  -5. 595.]
 [ 25.  -5. 595.]
 [ 15.   5. 595.]
 [ 25.   5. 595.]]
[[  5.   5. 585.]
 [ 15.   5. 585.]
 [  5.  15. 585.]
 [ 15.  15. 585.]
 [  5.   5. 595.]
 [ 15.   5. 595.]
 [  5.  15. 595.]
 [ 15.  15. 595.]]
[[ 15.   5. 585.]
 [ 25.   5. 585.]
 [ 15.  15. 585.]
 [ 25.  15. 585.]
 [ 15.   5. 595.]
 [ 25.   5. 595.]
 [ 15.  15. 595.]
 [ 25.  15. 595.]]
[[  5.  -5. 595.]
 [ 15.  -5. 595.]
 [  5.   5. 595.]
 [ 15.   5. 595.]
 [  5.  -5. 605.]
 [ 15.  -5. 605.]
 [  5.   5. 605.]
 [ 15.   5. 605.]]
[[ 15.  -5. 595.]
 [ 25.  -5. 595.]
 [ 15.   5. 595.]
 [ 25.   5. 595.]
 [ 15.  -5. 605.]
 [ 25.  -5. 605.]
 [ 15.   5. 605.]
 [ 25.   5. 605.]]
[[  5.   5. 595.]
 [ 15.   5. 595.]
 [  5.  15. 595.]
 [ 15.  15. 595.]
 [  5.   5. 605.]
 [ 15.   5. 605.]
 [  5.  15. 605.]
 [ 1

([pyvista_ndarray([  5.,  -5., 585.], dtype=float32),
  pyvista_ndarray([ 15.,  -5., 585.], dtype=float32),
  pyvista_ndarray([  5.,   5., 585.], dtype=float32),
  pyvista_ndarray([ 15.,   5., 585.], dtype=float32),
  pyvista_ndarray([  5.,  -5., 595.], dtype=float32),
  pyvista_ndarray([ 15.,  -5., 595.], dtype=float32),
  pyvista_ndarray([  5.,   5., 595.], dtype=float32),
  pyvista_ndarray([ 15.,   5., 595.], dtype=float32),
  pyvista_ndarray([ 15.,  -5., 585.], dtype=float32),
  pyvista_ndarray([ 25.,  -5., 585.], dtype=float32),
  pyvista_ndarray([ 15.,   5., 585.], dtype=float32),
  pyvista_ndarray([ 25.,   5., 585.], dtype=float32),
  pyvista_ndarray([ 15.,  -5., 595.], dtype=float32),
  pyvista_ndarray([ 25.,  -5., 595.], dtype=float32),
  pyvista_ndarray([ 15.,   5., 595.], dtype=float32),
  pyvista_ndarray([ 25.,   5., 595.], dtype=float32),
  pyvista_ndarray([  5.,   5., 585.], dtype=float32),
  pyvista_ndarray([ 15.,   5., 585.], dtype=float32),
  pyvista_ndarray([  5.,  15

In [26]:
# points is a 3D numpy array (n_points, 3) coordinates of a sphere
cloud = pv.PolyData(x)
print(cloud.points)
cloud.plot(point_size=4, color = "red")

[[  5.  -5. 585.]
 [ 15.  -5. 585.]
 [  5.   5. 585.]
 ...
 [ 55.  15. 605.]
 [ 45.  25. 605.]
 [ 55.  25. 605.]]


ViewInteractiveWidget(height=768, layout=Layout(height='auto', width='100%'), width=1024)

In [27]:
surf = cloud.delaunay_2d()
print(surf)
surf.plot(show_edges=True)

PolyData (0x7f90bc3610a0)
  N Cells:	129
  N Points:	384
  N Strips:	0
  X Bounds:	-5.000e+00, 5.500e+01
  Y Bounds:	-5.000e+00, 2.500e+01
  Z Bounds:	5.850e+02, 6.050e+02
  N Arrays:	0



ViewInteractiveWidget(height=768, layout=Layout(height='auto', width='100%'), width=1024)

In [55]:
'''
alphafloat, optional
Distance value to control output of this filter. For a non-zero alpha value, only vertices, edges, faces, or tetrahedra contained within the circumsphere (of radius alpha) will be output. Otherwise, only tetrahedra will be output.

tolfloat, optional
Tolerance to control discarding of closely spaced points. This tolerance is specified as a fraction of the diagonal length of the bounding box of the points.

offsetfloat, optional
Multiplier to control the size of the initial, bounding Delaunay triangulation.

progress_barbool, optional
Display a progress bar to indicate progress.
'''

volume = cloud.delaunay_3d(tol=0.001, alpha=15, offset=2.5)
shell = volume.extract_geometry()
type(shell)
shell.plot(show_edges=True)

pl = pv.Plotter()
pl.add_mesh(shell, show_edges=True)
pl.camera_position = 'yx'
pl.camera.zoom(1.2)
pl.show()

ViewInteractiveWidget(height=768, layout=Layout(height='auto', width='100%'), width=1024)

ViewInteractiveWidget(height=768, layout=Layout(height='auto', width='100%'), width=1024)

In [46]:
surf = cloud.reconstruct_surface(sample_spacing=10, nbr_sz = 10)
pl = pv.Plotter()
pl.add_points(cloud, color=(255,0,0))
pl.add_mesh(surf, show_edges=True)
pl.show()

ViewInteractiveWidget(height=768, layout=Layout(height='auto', width='100%'), width=1024)

In [ ]:
import numpy as np

import pyvista as pv

# Create an array of points
points = np.array(
    [
        [1.0, 0.0, 0.0],
        [0.0, 0.0, 0.0],
        [1.0, 1.0, 0.0],
        [0.0, 1.0, 0.0],
        [1.0, 2.0, 0.0],
        [0.0, 2.0, 0.0],
        [1.0, 3.0, 0.0],
        [0.0, 3.0, 0.0],
    ]
)

strips = np.array([8, 0, 1, 2, 3, 4, 5, 6, 7])


# build the mesh
mesh = pv.PolyData(points, strips=strips)
#mesh.plot()

pl = pv.Plotter()
pl.add_mesh(mesh, show_edges=True)
pl.add_point_labels(mesh.points, range(mesh.n_points))
pl.camera_position = 'yx'
pl.camera.zoom(1.2)
pl.show()


In [ ]:
import pyvista
sphere = pyvista.Sphere(theta_resolution=5, phi_resolution=5)
grid = sphere.delaunay_3d()
edges = grid.extract_all_edges()
edges.plot(line_width=1, color='k')

In [ ]:
import pyvista
center = np.array([0,0,0])
#bounds_min = center - spacing * 0.5
#bounds_max = center + spacing * 0.5

bounds = getBoxPointsBounds(center)

In [ ]:
bounds_min, bounds_max

In [ ]:

mesh = pyvista.Box(level=0, bounds=(bounds[0], bounds[1], bounds[2], bounds[3], bounds[4], bounds[4]))

#mesh.plot(show_edges=True)

pl = pv.Plotter()
pl.add_mesh(mesh, show_edges=True)
pl.add_points(mesh.points, color='red')
#pl.add_point_labels(mesh.points, range(mesh.n_points))
#pl.camera_position = 'xz'
#pl.camera.zoom(1.2)
pl.add_point_labels(mesh.points, mesh.points)
pl.show_axes()
pl.show()

mesh.points, np.amin(mesh.points)

In [ ]:
#cloud = mesh.points

volume = mesh.delaunay_3d(tol=5, alpha=10)
shell = volume.extract_geometry()
shell.plot(show_edges=True)